Updated Widget Link
The widget being used currently has less columns than the widget at
initial design. Links now open, but creates a new error on run.
java.lang.StringIndexOutOfBoundsException: String index out of range:
105
at java.lang.String.substring(Unknown Source)
at FootballParser.main(FootballParser.java:492)
Likely a change in the html of the widget.